config/routes.rb
Rails.application.routes.draw do
  resources :users


  get "/", to: "home#index"
  # get "users/new" => "users#new"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  post "/customer_details" => "users#owner", as: :add_owner

  post "/add_clerk" => "users#clerk", as: :addingclerk

  #menu category
  resources :menu_categories
  resources :menu_items

  put "customer_details" => "orders#update", as: :addstatus

  get "/customer_page" => "customer_pages#index", as: :customer_menupage
  get "/customer_menuitems" => "customer_items#index", as: :customer_menuitems
  patch "customer_menuitems", to: "users#updateaddress", as: :address



  patch "/menu_categories" => "menu_categories#updatemenustatus", as: :updatemenucategories
  patch "/menu_items" => "menu_items#updateitemstatus", as: :updateitemstatus

  resources :cart_items
  resources :orders
  resources :order_items
  resources :customer_details
  resources :show_carts
  resources :customer_dashboards
  resources :clerk_orders
  patch "/customer_dashboards", to: "users#edit_address", as: :change_address
end

app/controllers/customer_dashboards_controller.rb
class CustomerDashboardsController < ApplicationController
  def index
    render "index"
  end
end

app/views/customer_dashboards/index.html.erb
  <%if @current_user.role == "clerk" %>
      <%= render partial: "clerk_navbar/navbar" %>
    <%else %>
      <%= render partial: "navbar/nav" %>
    <% end %>

<div id="current-owner" >
  <img src="admin.png" alt="John" style="width:25%">
  <table style="width: 40%;">
    <tr>
      <td>Name: </td>
      <td>
        <div style="padding:15px"><%= @current_user.name %></div>
      </td>
    </tr>
    <tr>
      <td>Email: </td>
      <td>
        <div style="padding:15px"><%= @current_user.email %></div>
      </td>
    </tr>
    <tr>
      <td>Address:</td>
      <% if @current_user.address %>
        <td>
          <div style="padding:15px;word-break: break-word;"><%= @current_user.address %>

        <div style="padding:15px">
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Edit
              </button>
        </td>
        <% else %>
          <td>
            <div style="padding:15px">
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Add
              </button>
              <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content" style="width: 100%;">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Add Address</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <%= form_with(url: address_path, method: "patch", class: "AddAddress") do |form|%>
                        <%= form.text_area :address,class: "Addaddress-text", id: "message-text", required: true,autofocus: true %>
                        <%= form.submit("Add", class: "Addaddress-button") %>
                      <% end %>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </td>
          <% end %>
        </tr>
        <tr>
          <td colspan="2" style="text-align:center">
            <svg style="fill: #555;margin-right: 9px;
            position: relative;
            top: -3px;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill:rgba(0, 0, 0, 1);transform:;-ms-filter:"><path d="M18,2H6C5.447,2,5,2.447,5,3v9l5-4v3h6v2h-6v3l-5-4v9c0,0.553,0.447,1,1,1h12c0.553,0,1-0.447,1-1V3 C19,2.447,18.553,2,18,2z"></path></svg> <%= link_to "Sign Out", destroy_session_path, method: "delete" %></td>
        </tr>
      </table>
    </div>

 <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content" style="width: 100%;">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Add Address</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <%= form_with(url: change_address_path, method: "patch", class: "AddAddress") do |form|%>
                        <%= form.text_area :address,class: "Addaddress-text", id: "message-text", required: true,autofocus: true %>
                        <%= form.submit("Add", class: "Addaddress-button") %>
                      <% end %>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>