config/routes.rb
Rails.application.routes.draw do
  resources :users


  get "/", to: "home#index"
  # get "users/new" => "users#new"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  post "/customer_details" => "users#owner", as: :add_owner

  post "/add_clerk" => "users#clerk", as: :addingclerk

  #menu category
  resources :menu_categories
  resources :menu_items

  put "customer_details" => "orders#update", as: :addstatus

  get "/customer_page" => "customer_pages#index", as: :customer_menupage
  get "/customer_menuitems" => "customer_items#index", as: :customer_menuitems
  patch "customer_menuitems", to: "users#updateaddress", as: :address



  patch "/menu_categories" => "menu_categories#updatemenustatus", as: :updatemenucategories
  patch "/menu_items" => "menu_items#updateitemstatus", as: :updateitemstatus

  resources :cart_items
  resources :orders
  resources :order_items
  resources :customer_details
  resources :show_carts
  resources :customer_dashboards
  resources :clerk_orders
  patch "/customer_dashboards", to: "users#edit_address", as: :change_address
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to menu_categories_path
    else
      render "index"
    end
  end
end

app/views/home/index.html.erb
<head>
  <meta charset="utf-8">
  <title>SignUp Form</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="homepage.css" />
</head>
<body class="form-v2">
  <div class="page-content">
    <div class="form-content">
      <form class="form-detail" id="myform">
        <p class="introduction" style="margin-bottom: 36px;">Welcome to Our Cafeteria Management System</p>
        <div class="last-row-input">
          <%# <input type="submit" name="signup" class="signup" value="SignUp"> %>
          <%= link_to "Signup", new_user_path,class:"signup",style:"padding: 13px 30px 15px 30px;" %>
        </div>
        <div class="last-row-input" style="margin-top: 46px;margin-bottom: 21px;">
          <%# <input type="submit" name="signup" class="signup" value="SignIn"> %>
          <%= link_to "SignIn", new_sessions_path, class:"signup",style:"padding: 13px 30px 15px 30px;"  %>
        </div>
      </form>
    </div>
  </div>
</body>