config/routes.rb
Rails.application.routes.draw do
  resources :users


  get "/", to: "home#index"
  # get "users/new" => "users#new"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  post "/customer_details" => "users#owner", as: :add_owner

  post "/add_clerk" => "users#clerk", as: :addingclerk

  #menu category
  resources :menu_categories
  resources :menu_items

  put "customer_details" => "orders#update", as: :addstatus

  get "/customer_page" => "customer_pages#index", as: :customer_menupage
  get "/customer_menuitems" => "customer_items#index", as: :customer_menuitems
  patch "customer_menuitems", to: "users#updateaddress", as: :address



  patch "/menu_categories" => "menu_categories#updatemenustatus", as: :updatemenucategories
  patch "/menu_items" => "menu_items#updateitemstatus", as: :updateitemstatus

  resources :cart_items
  resources :orders
  resources :order_items
  resources :customer_details
  resources :show_carts
  resources :customer_dashboards
  resources :clerk_orders
  patch "/customer_dashboards", to: "users#edit_address", as: :change_address
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

    def create
      menuid= params[:id]
      quantity = params[:quantity]
      CartItem.create!(menu_item_id:menuid, quantity:quantity,user_id:@current_user.id)
      redirect_back(fallback_location:"/")
    end

    def update
      cart_item = current_user.cart_items.find_by(menu_item_id: params[:id])
      if cart_item && params[:quantity] == "1"
        cart_item.quantity += 1
      elsif(cart_item && cart_item.quantity > 0)
        cart_item.quantity -= 1
      else
        flash[:error]="something went wrong"
      end
      if cart_item.quantity == 0
        cart_item.destroy
      else
        cart_item.save!
      end
      redirect_back(fallback_location:"/")
    end

    def destroy
      cart_item = CartItem.find_by(menu_item_id: params[:id])
      cart_item.destroy
      redirect_back(fallback_location:"/")
    end
end

app/views/cart_items/_index.html.erb
<h1>Cart</h1>
<div id="cart-container" style="width:378px">
  <% arr = [] %>
  <div id="cartitemlist">
    <% @current_user.cart_items.all.each do |cart| %>
      <%if cart.quantity >=1 %>
        <div class="table-cart" style="word-wrap: break-word;word-spacing: 3px;text-align: end;">
          <div>Name:</div>
          <div><%= MenuItem.find(cart.menu_item_id).name %></div>
        </div>
        <div class="table-cart">
          <div>Quantity:</div>
          <div><%= cart.quantity %></div>
        </div>
        <% arr.push(MenuItem.find(cart.menu_item_id).price * cart.quantity.to_i) %>
        <hr>
      <% end %>
    <% end %>
    <div class="table-cart">
      <div>Total Price:</div>
      <div><%=  arr.sum %></div>
    </div>
  </div>
</div>
<div id="checkout-button" style="margin-bottom:200px">
  <div>
    <% if !@current_user.address.present? %>
      <button type="button" class="btn btn-primary" style="align-self: flex-end;
        color: #212529;
        background-color: #ffc107;
        border-color: #ffc107;
        width: 162px;
        border-radius: 4px;
        padding: 5px;
        margin-top: 16px;
        box-shadow: rgba(0, 0, 0, 0.25) 0px 0.0625em 0.0625em, rgba(0, 0, 0, 0.25) 0px 0.125em 0.5em, rgba(255, 255, 255, 0.1) 0px 0px 0px 1px inset;
        border-style: outset;
        " data-bs-toggle="modal" data-bs-target="#exampleModal">
        Checkout Item
      </button>
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content" style="width: 100%;">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add Address</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= form_with(url: address_path, method: "patch", class: "AddAddress") do |form|%>
                <%= form.text_area :address,class: "Addaddress-text", id: "message-text", required: true,autofocus: true %>
                <%= form.submit("Add", class: "Addaddress-button") %>
              <% end %>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div>
        <%= form_with(url: orders_path, method: "post", class: "checkout") do %>
          <%= submit_tag(" Checkout Item", class: "Addorders-button") %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>