config/routes.rb
Rails.application.routes.draw do
  resources :users


  get "/", to: "home#index"
  # get "users/new" => "users#new"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  post "/customer_details" => "users#owner", as: :add_owner

  post "/add_clerk" => "users#clerk", as: :addingclerk

  #menu category
  resources :menu_categories
  resources :menu_items

  put "customer_details" => "orders#update", as: :addstatus

  get "/customer_page" => "customer_pages#index", as: :customer_menupage
  get "/customer_menuitems" => "customer_items#index", as: :customer_menuitems
  patch "customer_menuitems", to: "users#updateaddress", as: :address



  patch "/menu_categories" => "menu_categories#updatemenustatus", as: :updatemenucategories
  patch "/menu_items" => "menu_items#updateitemstatus", as: :updateitemstatus

  resources :cart_items
  resources :orders
  resources :order_items
  resources :customer_details
  resources :show_carts
  resources :customer_dashboards
  resources :clerk_orders
  patch "/customer_dashboards", to: "users#edit_address", as: :change_address
end

app/views/clerk_navbar/_navbar.html.erb
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
<nav id="nav" class="nav" style="justify-content: space-between;">
  <button class="menu">
    <em class="hamburger"></em>
  </button>
  <div class="brand">
    <a href="javascript:void(0)">
      <i ></i>
      <%= link_to customer_menupage_path do %><%= image_tag "https://img.icons8.com/ios/50/000000/food-donor.png",style:"width: 24px;
    margin-right: 10px;" %>Authentic Dinning <% end %>
    </a>
  </div>
  <ul class="navbar">
    <li>
      <a href="javascript:void(0)">
        <%= link_to clerk_orders_path do %><%= image_tag "https://img.icons8.com/ios-glyphs/30/000000/shopping-bag.png", style:"width: 23px;
    margin-right: 10px;" %>Orders<% end %>
      </a>
    </li>
    <li>
      <a href="javascript:void(0)">
        <%= link_to show_carts_path do %><%= image_tag "https://img.icons8.com/ios/50/000000/favorite-cart.png",style:"width: 24px;
    margin-right: 19px;" %>Cart<% end %>
      </a>
    </li>
    <li>
      <%= link_to customer_dashboards_path do %>
        <%= image_tag "https://img.icons8.com/material-rounded/24/000000/user-male-circle.png" %> <%=@current_user.name%>
      <% end %>
    </li>
  </ul>
</nav>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
  /*http://callmenick.com/post/expanding-search-bar-using-css-transitions*/
  (function($) {
      "use strict";

      var $navigationbar = $(".nav"),
          y_pos = $navigationbar.offset().top,
          height = $navigationbar.height();

      //scroll top 0 sticky
      $(document).scroll(function() {
          var scrollTop = $(this).scrollTop();
          if (scrollTop > 0) {
            $navigationbar.addClass("sticky");
          } else {
            $navigationbar.removeClass("sticky");
          }
      });
  })(jQuery, undefined);

  $(".menu").click(function(){
    $("#nav").toggleClass("open");
  });
</script>